services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  flask:
    build: ./backend
    environment:
      - FLASK_APP=app
      - FLASK_ENV=${SET_FLASK_ENV}  # Enable Flask development mode
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app  # Mount local code for hot-reloading
    command: flask run --host=0.0.0.0
    depends_on:
      - db
      - redis

  vue:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app  # Mount local frontend code for hot-reloading
    command: npm run serve
    depends_on:
      - flask

volumes:
  postgres_data:
